// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgypvtqrzkpivdvnyyzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneXB2dHFyemtwaXZkdm55eXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDM3NjQsImV4cCI6MjA3MzUxOTc2NH0.q1jEA1uwF9Z8fDEkgh8z2Aa3IrAz30sswcjscdOLjsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});